services:
  llm-inference:
    container_name: llm-inference
    image: ghcr.io/ggml-org/llama.cpp:server
    platform: linux/amd64
    command: --model /models/gemma-3-12b-it-UD-Q4_K_XL.gguf --host 0.0.0.0 --port 11434 --ctx-size 2048
    ports:
      - "11434:11434"
    volumes:
      - ../../models/old/gguf:/models
    restart: unless-stopped
    networks:
      - app-network
  llm-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: llm-api
    ports:
      - "10010:10010"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  llm-inference-data:
  llm-chat-data:
  llm-chat-env:

networks:
  app-network:
    name: app-network
    external: true 
