services:
  llm-inference:
    container_name: llm-inference
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - llm-inference-data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
  llm-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: llm-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  llm-inference-data:

networks:
  app-network:
    name: app-network
    external: true 
