services:
  llm-inference:
    container_name: llm-inference
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - llm-inference-data:/root/.ollama
    restart: unless-stopped

volumes:
  llm-inference-data:

networks:
  app-network:
    external: true
    name: llm_app-network 
