services:
  llm-inference:
    container_name: llm-inference
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - llm-inference-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  llm-inference-data:

networks:
  app-network:
    external: true
    name: llm_app-network 
