services:
  llm-inference:
    container_name: llm-inference
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - llm-inference-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - app-network

volumes:
  llm-inference-data:

networks:
  app-network:
    name: app-network
    external: true 
