services:
  llm-inference:
    container_name: llm-inference
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - llm-inference-data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network

volumes:
  llm-inference-data:

networks:
  app-network:
    name: app-network
    external: true 
