services:
  llm-inference:
    container_name: llm-inference
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - llm-inference-data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
  llm-inference-2:
    container_name: llm-inference-2
    image: ghcr.io/ggerganov/llama.cpp:server
    platform: linux/arm64
    ports:
      - "8000:8000"
    environment:
      - MODEL=/models/Qwen3-14B-Q4_K_M.gguf
    volumes:
      - ../../models/gguf:/models
    restart: unless-stopped
    networks:
      - app-network
  llm-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: llm-api
    ports:
      - "10010:10010"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  llm-inference-data:
  llm-chat-data:
  llm-chat-env:

networks:
  app-network:
    name: app-network
    external: true 
