deployment:
  type: cpu

communication_layer:
  api:
    port: 8000
  webapp:
    port: 80

data_layer:
  relational_storage:
    port: 5432
    db: postgres
    auth_user: postgres
    auth_pass: fu27soma
  object_storage:
    port_ui: 9001
    port_api: 9000
  non_relational_storage:
    port: 6379
  vector_storage:
    port_rest: 6333
    port_grpc: 6334