services:
  management-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: management-api
    ports:
      - "10020:10020"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
  management-data:
    container_name: management-data
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true 
