services:
  communication-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: communication-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true 
