services:
  knowledge-relational:
    container_name: knowledge-relational
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  knowledge-object:
    container_name: knowledge-object
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /bitnami/minio/data --console-address ":9001"
    networks:
      - app-network

  knowledge-vector:
    container_name: knowledge-vector
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  knowledge-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: knowledge-api
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true 